return {
  "nvim-treesitter/nvim-treesitter",
  --commit = "4ae2b452e9bd67ff618e3bb0e3488e49c98465e9",
  opts = {
    ensure_installed = {
      "bash",
      "diff",
      "html",
      "javascript",
      "typescript",
      "c_sharp",
      "csv",
      "markdown",
      "markdown_inline",
      "regex",
      "rust",
      "toml",
      "vim",
      "vimdoc",
      "yaml",
      "terraform",
      "hcl",
      "query",
    },
    auto_install = true,
  },
}
